### ISSUE TITLE
Split the repo into two: native renderers (or macOS renderer) & platform-agnostic reconciler

### ISSUE THREAD

**Issue by jchavarri** [briskml/brisk#30]
This repo currently contains two separate things, both of them with enough substance on their own:

- The native renderers
- The reconciler

I'm not sure what Brisk exactly is 😄 but I wonder if you'd consider to separate both into two different repos.

We discussed with @wokalski the idea of replacing `reason-reactify` with `brisk` as the reconciler for `revery` , and I'd like to contribute / move docs + small examples that existed already in `reason-reactify`. But I thought it'd be more efficient to open this discussion before moving those assets here, or somewhere else.

- One idea could be to move just the reconciler to `reason-reactify` which is already isolated (and has the docs + examples that we could adapt to the new API).
- Or move it to a new `brisk-reconciler` repo.
- Another approach would be to leave the reconciler in `brisk` and take the macOS renderer (which I would expect to grow quite a lot over time?) into its own repo.

@wokalski @rauanmayemir @bryphe What do you think? Does the above make sense?

**Comment by wokalski** [comment]
Rauan and I have talked about this a few times. In general yes - I think they should be split. I think `brisk-reconciler` is a good place to put the reconciler 👍.

Also, to be open about it - I'd like the reconciler to stay in this repo/organization - at the same time I'm committing to maintaining it. Due to permissive licensing anyone is free to fork at any time and I'll be sure to transfer the repo when I won't be able to support it anymore (not anytime soon I think!)

**Comment by bryphe** [comment]
Thanks for logging the issue @jchavarri and the ideas!

> Also, to be open about it - I'd like the reconciler to stay in this repo/organization - at the same time I'm committing to maintaining it. 

I can understand that - I think it's fair since you're willing to maintain it! `brisk-reconciler` repo sounds good to me 👍 

> We discussed with @wokalski the idea of replacing reason-reactify with brisk as the reconciler for revery , and I'd like to contribute / move docs + small examples that existed already in reason-reactify. 

This sounds great, thank you for doing that! I think the 'web' and 'terminal' example are nice examples of a native reconciler in action - and it helps developers understand exactly the value it brings.

I think we'd have to think about `reason-reactify` in this new world - does it make sense to keep around? It might be that we could move the docs/examples wholesale to `brisk-reconciler` and could just archive that repo. 

`reason-reactify` could potentially be a thin 'adapter' over `brisk-reconciler` to preserve our previous semantics for the web/terminal examples... but not sure if there is actually any value in that.

It could be that the native element approach in `brisk-reconciler` actually simplifies the examples a bit, anyway - might be interesting to see. If we could have the docs / examples live in `brisk-reconciler`, I think that'd be ideal to complete the consolidation.

**Comment by rauanmayemir** [comment]
Just the other day we've been discussing that we'll need to make a split. Looks like it's not just us, I'll take care of the split today.

Docs and examples are greatly appreciated, thank you. 😁

**Comment by wokalski** [comment]
I think we should wait until the reconciler PR is  merged. Other than that I’m happy that we all agree 👏. going forward we will make sure to reference Revery wherever it’s applicable. People should have a choice and even when both projects are “production ready” there will be different trade offs involved.

**Comment by wokalski** [comment]
@bryphe after we're done with the migration we can also rename #reactify to #brisk-reconciler and possibly add a #experimental-reconcilers channel on the discord.

**Comment by bryphe** [comment]
> going forward we will make sure to reference Revery wherever it’s applicable. 

Thanks! 😄 

> People should have a choice and even when both projects are “production ready” there will be different trade offs involved.

Definitely. My belief is that it is really important to have both solutions: the 'flutter-style'-agnostic strategy as well as the ability to jump into truly-pure-native. You could even see a project using a mix - maybe `revery` for rapid prototyping cross-plat, and then `brisk` to jump in to get first-class platform integration. As you mentioned - different trade-offs 👍
