### ISSUE TITLE
Get rid of the Makefile for components-macos example

### ISSUE THREAD

**Issue by wokalski** [briskml/brisk#45]
We have three build tools/utilities involved:
- Make
- dune
- xcodebuild

Dune and xcodebuild are necessary but Make is just some weird leftover.

**Comment by rauanmayemir** [comment]
There's also a step for running `xcodegen` that since the addition of cache moved from the bootstrap phase to the run, i.e we run it every time on every build.

I think the process of calling xcodegen could be moved into `dune`, and then a single command for `xcodebuild` could be added in esy scripts.
